/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1.Grafo.Interfaz;

import proyecto1.Estructuras.Usuarios;
import proyecto1.Estructuras.List;
import proyecto1.Grafo.Grafico.MostrarGrafo;
import proyecto1.Estructuras.ListaAdyacencia;
import proyecto1.Estructuras.Grafo;
import proyecto1.Estructuras.Arco;
import proyecto1.Estructuras.NodoGrafo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.graphstream.graph.Node;

/**
 *
 * @author fabys
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    ListaAdyacencia lista = new ListaAdyacencia();
    MostrarGrafo grafo;
    List<String[]> lista_relaciones = new List<String[]>();
    File archivo;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        setTitle("Menu");

        System.setProperty("org.graphstream.ui", "swing");
        grafo = new MostrarGrafo(); // Inicializa la instancia de GraficoGrafo con 5 nodos

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Grafo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar Grafo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("      Bienvenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtroArchivo = new FileNameExtensionFilter("txt", "txt");
        seleccionarArchivo.setFileFilter(filtroArchivo);
        int seleccion = seleccionarArchivo.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File Archivo = seleccionarArchivo.getSelectedFile();
            archivo = Archivo;
            cargarArchivo(Archivo);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (this.ArchivoApto(archivo) == true) {

            grafo.mostrarGrafo(); // Llama al método mostrarGrafo() cuando se presiona el botón
            grafo.mostrarComponentesFuertementeConectados();

        } else {
            JOptionPane.showMessageDialog(null, "Ningun Archivo detectado!!", "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        VentanaModificarGrafo a = new VentanaModificarGrafo(grafo);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    public boolean ArchivoApto(File Archivo) {
        if (Archivo != null) {
            FileReader fr = null;
            BufferedReader br = null;
            try {
                fr = new FileReader(Archivo);
                br = new BufferedReader(fr);
                String linea;

                if (!(linea = br.readLine()).equals("usuarios")) {

                    return false;

                }

            } catch (Exception e) {
                e.printStackTrace();

            } finally {
                try {
                    if (fr != null) {
                        fr.close();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            return true;
        }
        return false;
    }

    public void cargarArchivo(File Archivo) {

        if (this.ArchivoApto(Archivo) == true) {

            FileReader fr = null;
            BufferedReader br = null;

            try {
                fr = new FileReader(Archivo);
                br = new BufferedReader(fr);

                String linea;
                int relaciones = 0;

                while ((linea = br.readLine()) != null) {

                    Usuarios u = new Usuarios();

                    String arreglo[] = linea.split(",");
                    //String arreglo2[] = linea.split(",");
                    if (relaciones == 0) {
                        System.out.println(arreglo[0]);
                        if (!linea.equals("usuarios") && !linea.equals("relaciones")) {
                            u.setUsuario(linea);
                            grafo.getGraph().addNode(linea);
                            grafo.getGrafo().nuevoNodo(linea);
                        }
                        if (linea.equals("relaciones")) {
                            relaciones++;
                        }

                    } else {

                        System.out.println(arreglo[0] + "," + arreglo[1]);
                        String origen = arreglo[0];
                        String destino = arreglo[1].replaceAll(" ", "");

                        lista_relaciones.addEnd(arreglo);
                        grafo.getGrafo().NuevoArco(origen, destino);
                        grafo.getGraph().addEdge(origen + "-" + destino, origen, destino, true);

                    }

                    lista.nuevaAdyacencia(u);
                }

            } catch (Exception e) {
                e.printStackTrace();

            } finally {
                try {
                    if (fr != null) {
                        fr.close();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Archivo Inválido!!", "InvalidInputException", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void modificarArchivo(MostrarGrafo grafo) throws IOException {
        FileWriter f = new FileWriter(archivo);
        PrintWriter w = new PrintWriter(f);
        NodoGrafo aux = grafo.getGrafo().getPrimero();
        w.write("usuarios" + "\n");

        while (aux != null) {
            w.write(aux.dato.toString() + "\n");
            System.out.println(aux.dato);

            aux = aux.siguiente;
        }
        w.write("relaciones" + "\n");

        proyecto1.Estructuras.Node<String[]> primero = lista_relaciones.getpFirst();

        while (primero != null) {
            w.write(primero.toString());
            System.out.println();
            primero.toString();
            primero = primero.getpNext();
        }
        w.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
